
name: Build and Run Tests # and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  #you can trigger workflow manualy with the below line from GitHub Actions
  workflow_dispatch:

jobs:

  build_and_npm_security_tests:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
        # original matrix [18.x, 20.x, 22.x]

    steps:
    - name: Checkout of the Repo  
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies         
      run: npm install

    - name: Runs "npm audit" Secirity Check   
      run: npm run test-npm-security


  build_and_integration_tests:
  
    runs-on: ubuntu-latest
    needs: build_and_npm_security_tests

    strategy:
      matrix:
        node-version: [20.x] 
        # original matrix [18.x, 20.x, 22.x]
       
    steps:
    - name: Checkout of the Repo  
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies         
      run: npm install

    - name: Run Integration Tests   
      run: npm test


#  deploy_on_render:
#    runs-on: ubuntu-latest
    #Jobs starts only if from branch main
    #if: github.ref == 'refs/heads/master'
#    needs: build_and_integration_tests
#    steps:
#      - name: Deploy to production
#        uses: johnbeynon/render-deploy-action@v0.0.8
#        with:
#          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
#          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          #wait-for-success: true
