
name: Build and Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # original matrix [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout of the Repo  
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies         
      run: npm install
      
    - name: Run Integration Tests   
      run: npm test
